### ISSUE TITLE
Error: Failed to parse block

### ISSUE THREAD

**Issue by Ozhiganov** [clintar/cryptonote-xmr-pool#10]
Help to understand the problem, when connecting to the pool, the miner issues an error

Error: Failed to parse block
at Object.BlockTemplate.nextBlob (/home/USER/fork/lib/pool.js:128:23)
at Object.Miner.getJob (/home/USER/fork/lib/pool.js:302:41)
at handleMinerMethod (/home/USER/fork/lib/pool.js:531:28)
at handleMessage (/home/USER/fork/lib/pool.js:660:13)
at Socket.socket.on.on.on.pushMessage (/home/USER/fork/lib/pool.js:714:25)
at Socket.emit (events.js:95:17)
at Socket. (stream_readable.js:765:14)
at Socket.emit (events.js:92:17)
at emitReadable (_stream_readable.js:427:10)
at emitReadable (_stream_readable.js:423:5)

2017-06-07 07:28:44 [master] Pool fork 1 died, spawning replacement worker...

**Comment by clintar** [comment]
sorry for delay. did you run latest monero for this?

**Comment by OfficiallyUndead** [comment]
Check node version...

Install NVM (Node Version Manager)
Install Node v0.10.25

Now clear node_modules folder and run npm update
