### ISSUE TITLE
My pool is not payment

### ISSUE THREAD

**Issue by mk148a** [clintar/cryptonote-xmr-pool#16]
Hi, i have itns pool. And ı use  https://github.com/clintar/cryptonote-xmr-pool pool . Everythinks work and i found 24blocks but no any payments and  any Pending Balance upgrade.

I think some settings be wrong.
My pool adress:https://intensecoin-pool.com/

I 'm share my config.

pool node config:
`{
    "coin": "INTENSE",
    "symbol": "ITNS",
    "coinUnits": 100000000,
    "coinDifficultyTarget": 120,

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "iz4BPZyUZdQQqjCQDkQJmTbkGpE1HrQKcRWPuCsYCX5MjjBocFmBlaBlaNTxGNCkCWHwS6r4EYoAbupWUUy9zcuiWAe1NFbRqs8C",
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "ports": [
            {
                "port": 3333,
                "difficulty": 1000,
                "desc": "Low end hardware"
            },
            {
                "port": 5555,
                "difficulty": 2000,
                "desc": "Mid range hardware"
            },
            {
                "port": 7777,
                "difficulty": 10000,
                "desc": "High end hardware"
            },
            {
                "port": 8080,
                "difficulty": 10000,
                "desc": "Alternate port"
            },
            {
                "port": 80,
                "difficulty": 10000,
                "desc": "Firewall Friendly Port"
            }

        ],
        "varDiff": {
            "minDiff": 2,
            "maxDiff": 200000,
            "targetTime": 100,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "fixedDiff": {
            "enabled": true,
            "addressSeparator": "."
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        }
    },

    "payments": {
        "enabled": true,
        "interval": 600,
        "maxAddresses": 50,
        "mixin": 0,
        "transferFee": 0.10,
        "minPayment": 500000000,
        "maxTransactionAmount": 0,
        "denomination": 100000000
    },

    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 60,
        "poolFee": 0.5,
        "devDonation": 0.1,
        "coreDevDonation": 0.1,
        "extraFeaturesDevDonation":0.1
    },

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 30,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "ssl": true,
        "sslport": 8119,
        "sslcert": "/etc/letsencrypt/live/intensecoin-pool.com/fullchain.pem",
        "sslkey": "/etc/letsencrypt/live/intensecoin-pool.com/privkey.pem",
        "sslca": "/etc/letsencrypt/live/intensecoin-pool.com/fullchain.pem",
        "password": "BlaBlaBla"
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 9998
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 8082
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

    "monitoring": {
        "daemon": {
            "checkInterval": 60,
            "rpcMethod": "getblockcount"
        },
        "wallet": {
            "checkInterval": 60,
            "rpcMethod": "getbalance"
        }
    },

    "charts": {
        "pool": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "workers": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "difficulty": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "price": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "profit": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            }
        },
        "user": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 180,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "payments": {
                "enabled": true
            }
        }
    }
}
`

My pool config.js

`var api = "https://intensecoin-pool.com:8119";

var poolHost = "intensecoin-pool.com";

var irc = "irc.freenode.net/#ITNS";

var email = "webmaster@intensecoin-pool.com";

var cryptonatorWidget = ["{symbol}-BTC", "{symbol}-USD", "{symbol}-EUR"];

var easyminerDownload = "https://github.com/zone117x/cryptonote-easy-miner/releases/";

var blockchainExplorer = "http://chainradar.com/{symbol}/block/{id}";

var transactionExplorer = "http://chainradar.com/{symbol}/transaction/{id}";

var themeCss = "themes/nightly-mining-dark-theme.css";
`

When i looking my admin panel i show about 38,7k ITNS on my pool wallet, but no payment yet why?

Please help me i dont know where is the problem.

**Comment by TateA** [comment]
Hey did you figure out how to fix this? If you did can you or someone let me know how to fix the pool. The ITNS coins team forked this code, but it seem it does not work. And they will not give any help to there community.

2017-12-03 22:01:28 Error with send_transaction RPC request to wallet daemon {"code":-1,"message":"JsonValue type is not INTEGER"}

**Comment by cryptogrot** [comment]
@mk148a @TateA Guys, how did you solve this issue ?
```
2018-01-17 03:00:08 [payments] Error with send_transaction RPC request to wallet daemon {"code":-1,"message":"JsonValue type is not INTEGER"}
2018-01-17 03:00:08 [payments] Payments failed to send to {"amount":1000000000,"address":"iz5FksdffjmBySXJ7vbJ9vK149p9TswHyubUFMKQv8MoK1QVDG3LQRL9jJp8DotYtPPvbNUdEgAZvaesrht1m"}
```

**Comment by markotdel** [comment]
@ mk148a @TateA @cryptogrot 
Guys, tell me how to solve the issue.
[payments] Error with send_transaction RPC request to wallet daemon {"code":-1,"message":"JsonValue type is not INTEGER"}

**Comment by cryptogrot** [comment]
@markotdel `transferFee` needs to be an integer. It could not be `0.15` for example.

**Comment by markotdel** [comment]
@cryptogrot 

Thank you, yes, I understood this, corrected. It seems to work, but periodically interrupted.
Displays:
TypeError: Can not read property 'pool' of undefined
    at / home /ubuntu/pool/lib/charts.js:148:30
    at ClientRequest. <anonymous> (/home/ubuntu/pool/lib/apiInterfaces.js:39:9)
    at ClientRequest.emit (events.js: 95: 17)
    at CleartextStream.socketErrorListener (http.js: 1610: 9)
    at CleartextStream.emit (events.js: 95: 17)
    at SecurePair. <anonymous> (tls.js: 1456: 15)
    at SecurePair.emit (events.js: 95: 17)
    at SecurePair.error (tls.js: 1067: 27)
    at EncryptedStream.CryptoStream._done (tls.js: 752: 22)
    at CleartextStream.read [as _read] (tls.js: 548: 24)

and 13 more such reports.
