### ISSUE TITLE
node makes me cry

### ISSUE THREAD

**Issue by Gingeropolous** [clintar/cryptonote-xmr-pool#2]
root@gbone-therock:/home/gbone/clintar_pool# npm update

> cryptonote-util@0.0.1 install /home/gbone/clintar_pool/node_modules/cryptonote-util
> node-gyp rebuild

module.js:442
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
cryptonote-universal-pool@0.0.1 /home/gbone/clintar_pool
└── multi-hashing@0.0.9  (git://github.com/clintar/node-multi-hashing.git#6df2cd104c0dcc5dceea216c1fcadbbbd0986552)

npm ERR! Linux 3.19.0-59-generic
npm ERR! argv "/root/.nvm/versions/node/v6.2.0/bin/node" "/root/.nvm/versions/node/v6.2.0/bin/npm" "update"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonote-util@0.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gbone/clintar_pool/npm-debug.log
root@gbone-therock:/home/gbone/clintar_pool# npm bugs cryptonote-util
npm ERR! Linux 3.19.0-59-generic
npm ERR! argv "/root/.nvm/versions/node/v6.2.0/bin/node" "/root/.nvm/versions/node/v6.2.0/bin/npm" "bugs" "cryptonote-util"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/cryptonote-util
npm ERR! 404
npm ERR! 404  'cryptonote-util' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gbone/clintar_pool/npm-debug.log
root@gbone-therock:/home/gbone/clintar_pool#

**Comment by Gingeropolous** [comment]
I fixed it. I don't know how, but I did.
