### ISSUE TITLE
Error: Failed to parse block

### ISSUE THREAD

**Issue by SgtTheDarknezz** [clintar/cryptonote-xmr-pool#31]
Error: Failed to parse block
    at Object.BlockTemplate.nextBlob (/home/coin/cryptonote-xmr-pool/lib/pool.js:129:23)
    at Object.Miner.getJob (/home/coin/cryptonote-xmr-pool/lib/pool.js:308:41)
    at handleMinerMethod (/home/coin/cryptonote-xmr-pool/lib/pool.js:510:28)
    at handleMessage (/home/coin/cryptonote-xmr-pool/lib/pool.js:645:13)
    at Socket.socket.on.on.on.pushMessage (/home/coin/cryptonote-xmr-pool/lib/pool.js:699:25)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)

Trying to run an aeon pool, am greeted with this, suggestions?

**Comment by clintar** [comment]
No idea. Never tried an aeon pool.

**Comment by SgtTheDarknezz** [comment]
i gave up anyways.
